### ISSUE TITLE
Language string missing

### ISSUE THREAD

**Issue by bogdanof** [modxcms/fred-rte-tinymce#4]
Got this problem after the last update:

<img width="1435" alt="screenshot 2018-10-22 13 33 50" src="https://user-images.githubusercontent.com/4386331/47288573-58eb6a00-d5ff-11e8-835a-c9d839084b32.png">

**Comment by rthrash** [comment]
Hi @bogdanof,

Are you still having this issue?

**Comment by bogdanof** [comment]
> Hi @bogdanof,
> 
> Are you still having this issue?

nope. update fixed this
