### ISSUE TITLE
Toolbar does not appear when selecting from middle to end.

### ISSUE THREAD

**Issue by muzzwood** [modxcms/fred-rte-tinymce#6]
The TinyMCE toolbar doesn't appear if text is selected from the middle to the end of the text block. 
Works fine the other way.
See gif:
![selecttext](https://user-images.githubusercontent.com/5160368/47827779-bb402980-ddba-11e8-87f8-44ad3dfcc487.gif)

**Comment by theboxer** [comment]
It's most likely caused by ending the select out of the tinymce area, which probably causes the field & editor to loose focus. I'm not sure how to fix this.

**Comment by matdave** [comment]
This is fixed by adding a setting for `selection_toolbar`
