### ISSUE TITLE
RTE outputs umlauts when user is logged in

### ISSUE THREAD

**Issue by valokammi** [modxcms/fred-rte-tinymce#7]
When logged in RTE renders all Scandinavian letters like ä,ö... in umlauts. Example in RTE Link text: käytössä is in editor (k&auml;yt&ouml;ss&auml;), this is not very useful for user.

Fred beta10, Revo 265.

**Comment by rthrash** [comment]
Hi @tassu,

I think this was fixed in a subsequent release. Can you confirm?

Thanks!
